name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Use Node.js
      uses: actions/setup-node@v4.03
      with:
        node-version: 20

    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9

    - name: Install dependencies (backend)
      working-directory: ./backend
      run: pnpm install

    - name: Lint backend
      working-directory: ./backend
      run: pnpm run lint

    - name: Format backend
      working-directory: ./backend
      run: pnpm run format

    - name: Install dependencies (frontend)
      working-directory: ./frontend
      run: pnpm install

    - name: Lint frontend
      working-directory: ./frontend
      run: pnpm run lint

    - name: Format frontend
      working-directory: ./frontend
      run: pnpm run format
