name: Test, lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      NODE_ENV: test
      PORT: 3000
      DB_TYPE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: test_user
      DB_PASS: test_password
      DB_NAME: test_db
      DB_SYNC: true
      JWT_SECRET: test_jwt_secret
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install dependencies (backend)
      working-directory: ./backend
      run: pnpm install

    - name: Lint backend
      working-directory: ./backend
      run: pnpm run lint

    - name: Format backend
      working-directory: ./backend
      run: pnpm run format

    - name: Unit test backend
      working-directory: ./backend
      run: pnpm run test

    - name: E2E test backend
      working-directory: ./backend
      run: pnpm run test:e2e

    - name: Install dependencies (frontend)
      working-directory: ./frontend
      run: pnpm install

    - name: Lint frontend
      working-directory: ./frontend
      run: pnpm run lint

    - name: Format frontend
      working-directory: ./frontend
      run: pnpm run format
